modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL = "https://github.com/TeamAuroraMods/EnhancedMushrooms/issues"
license = "All Rights Reserved"

[[mods]]
modId = "enhanced_mushrooms"
version = "6.0.0"
displayName = "Enhanced Mushrooms"
authors = "Team Aurora"
description = "Replaces Vanilla's overworld mushroom stems with a new woodset!"
logoFile="logo.png"

[[dependencies.enhanced_mushrooms]]
modId = "neoforge"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_mushrooms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.enhanced_mushrooms]]
modId = "blueprint"
mandatory = true
versionRange = "[8.1.0,]"
ordering = "BEFORE"
side = "BOTH"